# Generated by Django 2.1.9 on 2019-07-31 14:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Omra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank='true', default=datetime.datetime.now)),
                ('titre', models.CharField(blank='true', max_length=255)),
                ('slug', models.SlugField(max_length=400, null='true', unique='true')),
                ('ville_depart', models.CharField(blank='true', max_length=255)),
                ('aller', models.DateField(blank='true')),
                ('retour', models.DateField(blank='true')),
                ('escale', models.BooleanField(default='False')),
                ('nom_hotel_mekka', models.CharField(max_length=255, null='true')),
                ('etoiles_mekka', models.PositiveIntegerField(blank='true', null='true', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('nombre_nuit_mekka', models.PositiveIntegerField(blank='true')),
                ('distance_kaaba', models.PositiveIntegerField(blank='true', null='True')),
                ('nom_hotel_madina', models.CharField(max_length=255, null='true')),
                ('etoiles_madina', models.PositiveIntegerField(blank='true', null='true', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('nombre_nuit_madina', models.PositiveIntegerField(blank='true')),
                ('distance_masjid', models.PositiveIntegerField(blank='true', null='True')),
                ('prix', models.PositiveIntegerField(blank='true')),
                ('prix_chd', models.PositiveIntegerField(blank='true', default=0)),
                ('prix_chd2', models.PositiveIntegerField(blank='true', default=0)),
                ('prix_inf', models.PositiveIntegerField(blank='true', default=0)),
                ('commission', models.PositiveIntegerField(blank='true')),
                ('image', models.ImageField(blank='true', null='true', upload_to='omras')),
                ('image2', models.ImageField(blank='true', null='true', upload_to='omras')),
                ('image3', models.ImageField(blank='true', null='true', upload_to='omras')),
                ('image4', models.ImageField(blank='true', null='true', upload_to='omras')),
                ('description', models.TextField(blank='true')),
            ],
        ),
    ]
