# Generated by Django 2.1.9 on 2019-08-02 23:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omra',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
