# Generated by Django 2.1.9 on 2019-07-30 22:11

import datetime
import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank='true', default=datetime.datetime.now)),
                ('slug', models.SlugField(max_length=400, null='true', unique='true')),
                ('titre', models.CharField(blank='true', max_length=255)),
                ('destination', django_countries.fields.CountryField(blank='true', max_length=2)),
                ('ville_depart', models.CharField(blank='true', max_length=255)),
                ('nom_hotel', models.CharField(max_length=255, null='true')),
                ('etoiles', models.PositiveIntegerField(blank='true', null='true', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('aller', models.DateField(blank='true')),
                ('retour', models.DateField(blank='true')),
                ('transport', models.CharField(blank='true', choices=[('Avion', 'Avion'), ('Bus', 'Bus'), ('Bateau', 'Bateau')], max_length=255)),
                ('prix', models.PositiveIntegerField(blank='true')),
                ('prix_chd', models.PositiveIntegerField(blank='true', default=0)),
                ('prix_chd2', models.PositiveIntegerField(blank='true', default=0)),
                ('prix_inf', models.PositiveIntegerField(blank='true', default=0)),
                ('image', models.ImageField(blank='true', null='true', upload_to='voyages')),
                ('image2', models.ImageField(blank='true', null='true', upload_to='voyages')),
                ('image3', models.ImageField(blank='true', null='true', upload_to='voyages')),
                ('image4', models.ImageField(blank='true', null='true', upload_to='voyages')),
                ('description', models.TextField(blank='true')),
            ],
        ),
    ]
