# Generated by Django 2.1.9 on 2019-07-31 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='recu',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 3, 9, 19, 265569)),
        ),
    ]
