# Generated by Django 2.1.9 on 2019-08-02 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='recu',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 3, 0, 22, 20, 403562)),
        ),
    ]
