# Generated by Django 2.1.9 on 2019-07-30 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billeterie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recu', models.DateTimeField(default=datetime.datetime(2019, 7, 31, 0, 4, 29, 645561))),
                ('depart', models.CharField(max_length=120)),
                ('arrive', models.CharField(max_length=120)),
                ('dateAller', models.DateField()),
                ('dateRetour', models.DateField(blank=True, null=True)),
                ('classe', models.CharField(choices=[('economique', 'economique'), ('affaire', 'affaire'), ('premiere', 'premiere')], default='economique', max_length=15)),
                ('nbrAdulte', models.PositiveIntegerField()),
                ('nbrEnfant', models.PositiveIntegerField()),
                ('depart_multiple', models.CharField(blank=True, max_length=120, null=True)),
                ('arrive_multiple', models.CharField(blank=True, max_length=120, null=True)),
                ('dateAller_multiple', models.DateField(blank='True', null=True)),
                ('dateRetour_multiple', models.DateField(blank='True', null=True)),
                ('classe_multiple', models.CharField(choices=[('economique', 'economique'), ('affaire', 'affaire'), ('premiere', 'premiere')], default='economique', max_length=15)),
                ('nbrAdulte_multiple', models.PositiveIntegerField()),
                ('nbrEnfant_multiple', models.PositiveIntegerField()),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('telephone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
