# Generated by Django 2.1.9 on 2019-07-30 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetrie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billeterie',
            name='recu',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 0, 27, 41, 966603)),
        ),
    ]
