# Generated by Django 2.1.9 on 2019-08-02 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetrie', '0002_auto_20190803_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billeterie',
            name='recu',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 3, 0, 23, 44, 475767)),
        ),
    ]
