# Generated by Django 2.1.9 on 2019-07-31 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetrie', '0013_auto_20190731_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billeterie',
            name='recu',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 22, 54, 6, 836038)),
        ),
    ]
