# Generated by Django 2.1.9 on 2019-07-31 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoyageCarte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recu', models.DateTimeField(default=datetime.datetime(2019, 7, 31, 1, 52, 54, 698003))),
                ('destination', models.CharField(max_length=120)),
                ('ville', models.CharField(max_length=120)),
                ('dateAller', models.DateField()),
                ('dateRetour', models.DateField()),
                ('nbrAdulte', models.PositiveIntegerField()),
                ('nbrEnfant', models.PositiveIntegerField()),
                ('message', models.TextField(blank='True', null='True')),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('telephone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
