# Generated by Django 2.1.9 on 2019-07-31 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='recu',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 1, 52, 54, 697005)),
        ),
    ]
