# Generated by Django 2.1.9 on 2019-07-31 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20190731_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='recu',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 2, 54, 58, 994306)),
        ),
    ]
