# Generated by Django 2.1.9 on 2019-07-30 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransfertImage',
        ),
        migrations.DeleteModel(
            name='TransfertTitre1',
        ),
        migrations.AlterField(
            model_name='transfert',
            name='recu',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 0, 28, 8, 198900)),
        ),
    ]
