# Generated by Django 2.1.9 on 2019-08-02 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0003_auto_20190803_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfert',
            name='recu',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 3, 0, 40, 18, 354818)),
        ),
    ]
