# Generated by Django 2.1.9 on 2019-07-31 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0004_auto_20190731_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfert',
            name='recu',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 2, 8, 17, 991468)),
        ),
    ]
