# Generated by Django 2.1.9 on 2019-07-31 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0006_auto_20190731_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfert',
            name='recu',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 3, 9, 19, 262577)),
        ),
    ]
