# Generated by Django 2.1.9 on 2019-07-31 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0011_auto_20190731_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfert',
            name='recu',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 22, 50, 58, 355544)),
        ),
    ]
